# Generated by Django 4.1.1 on 2022-09-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0008_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
