# Generated by Django 4.1.1 on 2022-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0010_alter_questioner_q0_alter_questioner_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioner',
            name='Q0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q15',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q16',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q17',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q18',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q19',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q21',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q22',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q23',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q24',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='Q9',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questioner',
            name='allergy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='chills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fatigue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fever',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='feverish',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='headache',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='induration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='itch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='join_pain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='muscle_ache',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='nausea',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='redness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='swelling',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='tenderness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='vomiting',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='warmth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
