# Generated by Django 4.1.1 on 2022-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0011_alter_questioner_q0_alter_questioner_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioner',
            name='allergy1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioner',
            name='allergy2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioner',
            name='allergy3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioner',
            name='allergy4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioner',
            name='allergy5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
