# Generated by Django 4.1.1 on 2023-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0019_alter_questioner_author_alter_sideeffect_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffectyes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
