# Generated by Django 4.1.1 on 2023-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0020_alter_sideeffectyes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffectyes',
            name='btnYes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
