# Generated by Django 4.1.1 on 2023-04-03 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0021_alter_sideeffectyes_btnyes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffectyes',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
