# Generated by Django 4.1.1 on 2023-04-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0022_sideeffectyes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffectyes',
            name='date',
        ),
    ]
