# Generated by Django 4.1.1 on 2023-04-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0023_remove_sideeffectyes_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sideeffectYes',
        ),
    ]
