# Generated by Django 4.1.1 on 2023-04-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0024_delete_sideeffectyes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='report',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='vaccimo.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='chills',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fatigue',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fever',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='feverish',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='headache',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='induration',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='itch',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='join_pain',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='muscle_ache',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='name',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='nausea',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='redness',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='swelling',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='tenderness',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='vomiting',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='warmth',
            field=models.DateField(auto_now=True, default='vaccimo'),
            preserve_default=False,
        ),
    ]
