# Generated by Django 4.1.1 on 2023-04-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0025_sideeffect_report_alter_sideeffect_chills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='report',
        ),
        migrations.AlterField(
            model_name='questioner',
            name='allergy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccimo.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='itch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccimo.questioner'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='tenderness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccimo.user'),
        ),
    ]
